resources:
- name: s3pypi-ci-image
  type: git
  check_every: 24h
  source:
    uri: https://github.com/jonm/s3pypi-ci-image.git
    branch: master

- name: hub
  type: docker-image
  check_every: 24h
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: jonm33/s3pypi-ci

jobs:
- name: publish
  public: true
  serial: true
  plan:
    - get: s3pypi-ci-image
      trigger: true
    - put: hub
      params:
        build: s3pypi-ci-image
        cache: true
        cache_tag: latest
        tag_file: s3pypi-ci-image/VERSION
        tag_as_latest: true
      get_params: {skip_download: true}
